# Generated by Django 3.1.2 on 2020-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('place_introduce', models.TextField()),
                ('place_caution', models.CharField(max_length=200)),
                ('place_image', models.ImageField(blank=True, upload_to='media/')),
                ('place_address', models.CharField(max_length=100)),
                ('place_postcode', models.CharField(max_length=100)),
                ('place_detailAddress', models.CharField(max_length=100)),
                ('place_extraAddress', models.CharField(max_length=100)),
                ('place_price', models.CharField(max_length=100)),
                ('registered_dttm', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
