# Generated by Django 2.2.1 on 2020-10-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_introduce', models.TextField()),
                ('project_category', models.CharField(max_length=200)),
                ('project_image', models.ImageField(blank=True, upload_to='media/')),
                ('funding_price', models.CharField(max_length=100)),
                ('funded_price', models.CharField(max_length=100)),
                ('funding_startday', models.CharField(max_length=100)),
                ('funding_starttime', models.CharField(max_length=100)),
                ('funding_endday', models.CharField(max_length=100)),
                ('funding_endtime', models.CharField(max_length=100)),
                ('project_ticketprice', models.CharField(max_length=100)),
                ('funding_bank', models.CharField(max_length=100)),
                ('funding_account', models.CharField(max_length=100)),
                ('registered_dttm', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
