# Generated by Django 2.2.1 on 2020-10-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirim', '0004_auto_20201025_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='funded_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='funding',
            name='funding_price',
            field=models.IntegerField(null=True),
        ),
    ]
