# Generated by Django 2.2.1 on 2020-10-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirim', '0007_auto_20201025_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='funding_endday',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='funding',
            name='funding_endtime',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='funding',
            name='funding_startday',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='funding',
            name='funding_starttime',
            field=models.CharField(max_length=4),
        ),
    ]
